---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n-database
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: databases
  chart:
    spec:
      chart: cluster
      version: ">=0.0.10"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: cnpg
      namespace: flux-system
  values:
    type: postgresql
    mode: standalone
    version:
      postgresql: "18"
    cluster:
      instances: 1
    backups:
      enabled: false
    bootstrap:
      initdb:
        database: n8n
        owner: n8n
