---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: flux-system
  labels:
    app: n8n
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: n8n
  chartRef:
    kind: OCIRepository
    name: n8n-ocirepo
    namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: "2.0.0-rc.4"
    # Database configuration
    config:
      database:
        type: postgresdb
        postgresdb:
          host: n8n-n8n-database-cluster-rw
          port: 5432
          database: n8n
          user: n8n
          password:
            fromSecret:
              name: n8n-n8n-database-cluster-app
              key: password

    # Persistence for n8n data
    persistence:
      enabled: true
      size: 10Gi
      storageClass: local-path

    # Ingress configuration (disabled for now, will use Gateway API)
    ingress:
      enabled: false

    # Service configuration
    service:
      type: ClusterIP
      port: 5678

    # Resources
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
