---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - outline-pvc.yaml
  - outline-db-helmrelease.yaml
  - outline-valkey.yaml
  - outline-helmrepo.yaml
  - outline-helmrelease.yaml
  - outline-httproute.yaml