---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - warpgate-gitrepository.yaml
  - warpgate-db-helmrelease.yaml
  - warpgate-pvc.yaml
  - warpgate-helmrelease.yaml
  - warpgate-destinationrule.yaml
