apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warpgate-pvc
  namespace: warpgate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
