---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: base
      version: ">=1.24.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1h
  targetNamespace: istio-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  releaseName: istio-base
