---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: flux-system
  labels:
    app: forgejo
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: forgejo
  chartRef:
    kind: OCIRepository
    name: forgejo-ocirepo
    namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      claimName: forgejo-pvc
      size: 30Gi
    gitea:
      config:
        service:
          DISABLE_REGISTRATION: "true"
        mailer:
          ENABLED: "true"
          SMTP_ADDR: "smtp-relay.gmail.com"
          SMTP_PORT: 587
          FROM: "auth@kubespaces.io"
          USER: "alessandro@kubespaces.io"
        server:
          DOMAIN: code.vps.kubespaces.cloud
          ROOT_URL: "https://code.vps.kubespaces.cloud/"
        database:
          DB_TYPE: postgres
          HOST: forgejo-forgejo-database-cluster-rw
      additionalConfigFromEnvs:
        - name: FORGEJO__MAILER__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-smtp
              key: passwd
        - name: FORGEJO__DATABASE__NAME
          valueFrom:
            secretKeyRef:
              name: forgejo-forgejo-database-cluster-app
              key: dbname
        - name: FORGEJO__DATABASE__USER
          valueFrom:
            secretKeyRef:
              name: forgejo-forgejo-database-cluster-app
              key: user
        - name: FORGEJO__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-forgejo-database-cluster-app
              key: password