---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: keycloak-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://epam.github.io/edp-helm-charts/stable
