---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - buzz-ocirepository.yaml
  - buzz-db-helmrelease.yaml
  - buzz-silo.yaml
  - buzz-valkey.yaml
  - buzz-helmrelease.yaml
