---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - twenty-db-helmrelease.yaml
  - twenty-pvc.yaml
  - twenty-helmrelease.yaml
  - twenty-httproute.yaml
