apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twenty-pvc
  namespace: twenty
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
